### ISSUE TITLE
XDG data vs state dir

### ISSUE THREAD

**Issue by Konfekt** [CodesOfRishi/navita#1]
Thank you for this useful tool. I was looking for a shell script replacing z.sh now that it no longer works under ZSH. 

Just as a suggestion: Would the data stored by Navita not be more akin to an `$XDG_STATE` rather than `$XDG_DATA` dir?

**Comment by CodesOfRishi** [comment]
Are you suggesting the data files like history files should be in `XDG_STATE_HOME` instead of `XDG_DATA_HOME` by default?

**Comment by Konfekt** [comment]
Yes, I thought so, it seems rather a [state](https://specifications.freedesktop.org/basedir-spec/latest/) than more static data, no high stakes though

**Comment by CodesOfRishi** [comment]
Yes, by definition, it seems the `$XDG_STATE_HOME` directory fits better for such kind of files. I think I'll implement this. Thanks for bringing this up!

**Comment by Konfekt** [comment]
How about `$NAVITA_DATA_DIR/navita-history` ?

**Comment by CodesOfRishi** [comment]
Name change for the `NAVITA_DATA_DIR` environment variable as well you mean?

I think I will let it be. Not really necessary or critical since it's just a name that doesn't really deviates from its intended role. I think important here is the default value that is `XDG_STATE_HOME`.

Also there are no any such files being stored in `XDG_DATA_HOME` directory for Navita script. If in future there's such need, I may make necessary changes.

**Comment by Konfekt** [comment]
Very sensible, In fact, I just misread `$XDG_DATA_DIR` instead of `$NAVITA_DATA_DIR`.
